name: Scala Maven CI

on:
  push:
    branches:
      - scala_

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - scala-version: 2.13.11
            profile: scala-2
          - scala-version: 3.3.1
            profile: scala-3

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B clean compile -Dscala.version=${{ matrix.scala-version }} -P${{ matrix.profile }}

      - name: Run Main
        run: mvn exec:java -Dscala.version=${{ matrix.scala-version }} -P${{ matrix.profile }} -Dexec.mainClass=Main
