name: Build and Run Cypress Program

on:
  push:
    branches:
      - cypress_testing  # or your default branch name
  pull_request:
    branches:
      - cypress_testing  #  or your default branch name

jobs:
  build:
    runs-on: ubuntu-latest  # You can change to other operating systems like 'windows-latest' if necessary

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
         npm install --save-dev cypress
         npm install

      - name: Install dependencies
        run: npx cypress run

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Application docker
        run: |
          docker build -t cypress-tests .
          docker run --rm cypress-tests
          docker tag cypress-tests sreedockerhub19/cypress-tests:latest
          docker push sreedockerhub19/cypress-tests:latest

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: executed_notebooks
          path: |
            cypress/results/cypress-mochawesome-reporter/index.html
            cypress/results/cypress-mochawesome-reporter/videos
