name: Swift Hello World

on:
  push:
    branches:
      - swift_  # Trigger on push to master branch

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: swift:5.10
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Verify Swift version
        run: swift --version


      # Run the Swift program
      # Mac: #/Users/runner/hostedtoolcache/swift-macOS/5.7.3/arm64/usr/bin/swift
      - name: Run Hello World
        run: |
          folder="execute"
          for file in $(find "$folder" -type f -name "*.swift"); do
            swift "$file"
          done

          echo 'print("Hello, Swift from the workflow shell!" + ":2")' | swift repl

